version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: study_buddy_postgres
    environment:
      POSTGRES_DB: study_buddy
      POSTGRES_USER: study_buddy_user
      POSTGRES_PASSWORD: study_buddy_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./data/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - study_buddy_network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: study_buddy_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - study_buddy_network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: study_buddy_backend
    environment:
      - DATABASE_URL=postgresql://study_buddy_user:study_buddy_password@postgres:5432/study_buddy
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - DEBUG=True
      - ENVIRONMENT=development
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./data/uploads:/app/uploads
    depends_on:
      - postgres
      - redis
    networks:
      - study_buddy_network
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  # Celery Worker
  celery_worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: study_buddy_celery_worker
    environment:
      - DATABASE_URL=postgresql://study_buddy_user:study_buddy_password@postgres:5432/study_buddy
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
    volumes:
      - ./backend:/app
    depends_on:
      - postgres
      - redis
    networks:
      - study_buddy_network
    command: celery -A app.celery_app worker --loglevel=info

  # Celery Beat (Scheduler)
  celery_beat:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: study_buddy_celery_beat
    environment:
      - DATABASE_URL=postgresql://study_buddy_user:study_buddy_password@postgres:5432/study_buddy
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
    volumes:
      - ./backend:/app
    depends_on:
      - postgres
      - redis
    networks:
      - study_buddy_network
    command: celery -A app.celery_app beat --loglevel=info

  # Flower (Celery Monitoring)
  flower:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: study_buddy_flower
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
    ports:
      - "5555:5555"
    depends_on:
      - redis
    networks:
      - study_buddy_network
    command: celery -A app.celery_app flower --port=5555

  # pgAdmin (Database Administration)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: study_buddy_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@studybuddy.ai
      PGADMIN_DEFAULT_PASSWORD: admin_password
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - study_buddy_network

volumes:
  postgres_data:
  redis_data:
  pgadmin_data:

networks:
  study_buddy_network:
    driver: bridge